[metadata]
format.version = "1.1"

[versions]
assertj = "3.26.3"
junit = "1.10.3"
jupiter = "5.10.3"
okhttp = "4.12.0"
tck = "0.0.1-SNAPSHOT"

[libraries]
tck-common-api = {module = "org.eclipse.dataspacetck:core-api", version.ref = "tck"}

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junit" }
markdown-gen = { module = "net.steppschuh.markdowngenerator:markdowngenerator", version = "1.3.1.1" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
plantuml = { module = "net.sourceforge.plantuml:plantuml", version = "1.2024.8" }


[plugins]
nexuspublishing = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
# needed for the "dockerize" task
docker = { id = "com.bmuschko.docker-remote-api", version = "9.4.0" }
# needed to build a fat JAR
shadow = { id = "com.gradleup.shadow", version = "8.3.5" }

gradle-publish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
